### ISSUE TITLE
Sudo needs to be a prerequisite

### ISSUE THREAD

**Issue by tr33m4n** [BunsenLabs/bunsen-installscripts#3]
Hello there,

The install scripts failed for me initially as they rely on the base system having sudo installed, there should probably be a check for this

Cheers
Dan

**Comment by johnraff** [comment]
Sorry, but there are no install scripts at the moment. When we upload something we'll keep your suggestion in mind. Thank you for taking the time to visit BunsenLabs.

**Comment by johnraff** [comment]
Please see here:
https://github.com/BunsenLabs/bunsen-installscripts/pull/2#issuecomment-93220379

**Comment by tr33m4n** [comment]
Ah, I apologies, I was running someone else's fork and the readme pointed me to this issue queue to report bugs

**Comment by johnraff** [comment]
No problem - thank you for your interest in BunsenLabs!
